package com.debritsu.app.data

/**
 * Where [Settings] keeps what it is told.
 *
 * The whole of the Android coupling in settings was one `SharedPreferences`
 * handle, so this is the shape of that and nothing more. Android backs it with
 * SharedPreferences; a desktop build backs it with a file. The keys are the
 * settings' own, so the two are reading the same names — which matters if a
 * profile is ever moved between them.
 *
 * Deliberately not `suspend`. Every caller reads these synchronously today, and
 * making them suspending would spread coroutines through the settings screen and
 * the source filter to no benefit: the Android implementation is a memory-backed
 * map with an asynchronous write behind it, and a file is a few microseconds.
 */
interface KeyValueStore {
    fun getString(key: String, fallback: String): String
    fun putString(key: String, value: String)

    fun getInt(key: String, fallback: Int): Int
    fun putInt(key: String, value: Int)

    fun getLong(key: String, fallback: Long): Long
    fun putLong(key: String, value: Long)

    fun getFloat(key: String, fallback: Float): Float
    fun putFloat(key: String, value: Float)

    fun getBoolean(key: String, fallback: Boolean): Boolean
    fun putBoolean(key: String, value: Boolean)

    fun remove(key: String)

    /**
     * Every key currently held.
     *
     * For the stores that are a collection rather than a fixed set of settings:
     * resume positions are keyed by show and episode, and the offline queue by
     * media id, so neither can be read without asking what is in there.
     */
    fun keys(): Set<String>
}

/**
 * Answers everything with the fallback and forgets every write.
 *
 * So that reading a setting before the host has installed a real store returns
 * the default rather than throwing. A crash there would be at startup, in
 * whichever unrelated thing happened to read a setting first, and would read as
 * anything but "the store was not installed yet".
 */
internal object NoStore : KeyValueStore {
    override fun getString(key: String, fallback: String) = fallback
    override fun putString(key: String, value: String) = Unit
    override fun getInt(key: String, fallback: Int) = fallback
    override fun putInt(key: String, value: Int) = Unit
    override fun getLong(key: String, fallback: Long) = fallback
    override fun putLong(key: String, value: Long) = Unit
    override fun getFloat(key: String, fallback: Float) = fallback
    override fun putFloat(key: String, value: Float) = Unit
    override fun getBoolean(key: String, fallback: Boolean) = fallback
    override fun putBoolean(key: String, value: Boolean) = Unit
    override fun remove(key: String) = Unit
    override fun keys(): Set<String> = emptySet()
}

/**
 * The few things about the running build that the shared code needs and cannot
 * work out for itself.
 *
 * These came from `BuildConfig`, which is generated by the Android build and
 * does not exist off it. Set once at startup, from whatever the host knows.
 */
object BuildInfo {
    /** Extra logging. False unless the host says otherwise. */
    var debug: Boolean = false

    /**
     * Where a debug line goes. Discarded unless the host wires it up.
     *
     * Android sends these to `android.util.Log.d`, which is where the
     * `DebritsuFilter` and `DebritsuSubs` tags documented in CLAUDE.md are read
     * from. A desktop build would send them to stdout. The tag is passed rather
     * than assumed because those tag names are what makes a logcat filter
     * usable at all.
     */
    var log: (tag: String, message: String) -> Unit = { _, _ -> }

    /**
     * The AniList client baked into this build, used when the user has not
     * supplied one of their own. Each front end registers its own client — the
     * redirect URL is per client and per platform.
     */
    var anilistClientId: String = ""
}
